AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  warattel

  Sample SAM Template for warattel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  TelegramBotToken:
    Type: String
  TelegramWebhookUrl:
    Type: String
Resources:
  TelegramHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_WEBHOOK_URL: !Ref TelegramWebhookUrl
      CodeUri: src
      Handler: lambda_app.warattel_lambda_handler
      Runtime: python3.7
      Events:
        TelegramHandler:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /warattel
            Method: post