AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  warattel

  Sample SAM Template for warattel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TelegramHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app_lambda/msg_handler.the_handler
      Runtime: python3.7
      Events:
        TelegramHandler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: 
              post
              get
  # GetWebhookFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: .
  #     Handler: app_lambda/webhook_handler.get_webhook_info_lambda_handler
  #     Runtime: python3.7
  #     Events:
  #       HandleUpdate:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /
  #           Method: get 
  # SetWebhookFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: .
  #     Handler: app_lambda/webhook_handler.set_webhook_info_lambda_handler
  #     Runtime: python3.7
  #     Events:
  #       HandleUpdate:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /set_webhook
  #           Method: get 

Outputs:
  WebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/handle_update/"
  TelegramHandlerFunction:
    Description: "Handle Telegram Update Lambda Function ARN"
    Value: !GetAtt TelegramHandlerFunction.Arn
  TelegramHandlerFunctionRole:
    Description: "Implicit IAM Role created for Webhook function"
    Value: !GetAtt TelegramHandlerFunctionRole.Arn
