version: 2.1

orbs:
  python: circleci/python@1.2
  sam: circleci/aws-sam-serverless@2.1.0
workflows:
  sample: 
     jobs:
      - build:
          context: aws_personal
      - hold: 
          type: approval
          requires:
            - build
      - deploy:
          context: aws_personal
          requires:
            - hold
jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - sam/install
      - python/install-packages:
          pkg-manager: pip
      - run: 
          name: "Sam Build"
          command: sam build
  deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - run: 
          name: "Sam deploy"
          command: sam deploy


