version: 2.1

orbs:
  python: circleci/python@1.2
  sam: circleci/aws-sam-serverless@2.1.0
workflows:
  sample: 
     jobs:
      - hold: 
          type: approval
      - build-and-deploy:
          context: aws_personal
          requires:
            - hold
jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - sam/install
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Setup Environment Variables
          command: |
            echo "export DB_CONNECTION_STRING=$DB_CONNECTION_STRING" >> secrets.txt
            echo "export DB_NAME=$DB_NAME" >> secrets.txt
            echo "export TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> secrets.txt
            echo "export TELEGRAM_WEBHOOK_URL=$TELEGRAM_WEBHOOK_URL" >> secrets.txt
      - run: 
          name: "Sam Build"
          command: sam build
      - run: 
          name: "Sam deploy"
          command: sam deploy --parameter-overrides ParameterKey=TelegramBotToken,ParameterValue=${TELEGRAM_BOT_TOKEN} ParameterKey=TelegramWebhookUrl,ParameterValue=${TELEGRAM_WEBHOOK_URL}



